CREATE DATABASE SCHOOL
go
USE SCHOOL

-- TAI KHOAN
CREATE TABLE TAIKHOAN(
	TAIKHOAN VARCHAR(255) NOT NULL PRIMARY KEY,
	MATKHAU VARCHAR(256) NOT NULL,
	ROLE VARCHAR(10),
	TRANGTHAI VARCHAR(10)
)
SELECT * FROM TAIKHOAN WHERE ROLE <> 'ADMIN'
INSERT INTO TAIKHOAN VALUES
('x', 'b', 'a', 'ACTIVE')

-- LOAI THONG BAO
CREATE TABLE LOAITHONGBAO(
	IDLOAITHONGBAO INT IDENTITY(1,1) PRIMARY KEY,
	TEN NVARCHAR(100)
)
INSERT INTO LOAITHONGBAO VALUES
(N'Học Phí'),
(N'Lịch Nghỉ'),
(N'Hoạt Động')


-- THONG BAO
CREATE TABLE THONGBAO(
	IDTHONGBAO INT IDENTITY(1,1) PRIMARY KEY,
	TIEUDE NVARCHAR(100),
	NOIDUNG NVARCHAR(500),
	NGAYDANG DATE,
	IDLOAITHONGBAO INT,
)

INSERT INTO THONGBAO VALUES
(N'Title 1', N'Content 1', '4-4-2020', 1),
(N'Title 2', N'Content 2', '4-4-2020', 2),
(N'Title 3', N'Content 3', '4-4-2020', 3)

SELECT * FROM THONGBAO, LOAITHONGBAO WHERE THONGBAO.IDLOAITHONGBAO = LOAITHONGBAO.IDLOAITHONGBAO
SELECT * FROM LOAITHONGBAO 
SELECT * FROM NAMHOC 
CREATE TABLE NAMHOC(
	IDNAMHOC INT IDENTITY(1,1) PRIMARY KEY,
	TENNAMHOC NVARCHAR(50),
	NGAYBATDAU DATE,
	NGAYKETTHUC DATE,
	TRANGTHAI NVARCHAR(50)
)
SELECT * FROM HOCKY, NAMHOC WHERE HOCKY.IDNAMHOC = NAMHOC.IDNAMHOC
CREATE TABLE HOCKY(
	IDHOCKY  INT IDENTITY(1,1) PRIMARY KEY,
	IDNAMHOC VARCHAR(10) NOT NULL,
	TENHOCKY NVARCHAR(50),
	NGAYBATDAU DATE,
	NGAYKETTHUC DATE,
	TRANGTHAI NVARCHAR(50)
)
INSERT INTO NAMHOC VALUES
('2021 - 2022', '4-4-2020', '5-5-2020', 'END'),
('2022 - 2023', '4-4-2020', '5-5-2020', 'END')

INSERT INTO HOCKY VALUES
(1, 'HK1' ,'4-4-2020', '5-5-2020', 'END'),
(1, 'HK2' ,'4-4-2020', '5-5-2020', 'END'),
(2, 'HK1' ,'4-4-2020', '5-5-2020', 'END'),
(2, 'HK2' ,'4-4-2020', '5-5-2020', 'END')

