CREATE DATABASE SCHOOL
go
USE SCHOOL
GO
-- TAI KHOAN
CREATE TABLE TAIKHOAN(
	TAIKHOAN VARCHAR(255) NOT NULL PRIMARY KEY,
	MATKHAU VARCHAR(256) NOT NULL,
	ROLE VARCHAR(10),
	TRANGTHAI VARCHAR(10)
)

INSERT INTO TAIKHOAN VALUES
('admin', '$2a$12$O7zJkruHOIKWrZhp8XKiq.eOW1mZPclUE0L3x6Ic8CwVI25Njd52O', 'ADMIN', 'ACTIVE')

-- LOAI THONG BAO
CREATE TABLE LOAITHONGBAO(
	IDLOAITHONGBAO INT IDENTITY(1,1) PRIMARY KEY,
	TEN NVARCHAR(100)
)
INSERT INTO LOAITHONGBAO VALUES
(N'Học Phí'),
(N'Lịch Nghỉ'),
(N'Hoạt Động')


-- THONG BAO
CREATE TABLE THONGBAO(
	IDTHONGBAO INT IDENTITY(1,1) PRIMARY KEY,
	TIEUDE NVARCHAR(100),
	NOIDUNG NVARCHAR(500),
	NGAYDANG DATE,
	IDLOAITHONGBAO INT,
)


CREATE TABLE NAMHOC(
	IDNAMHOC INT IDENTITY(1,1) PRIMARY KEY,
	TENNAMHOC NVARCHAR(50),
	NGAYBATDAU DATE,
	NGAYKETTHUC DATE,
	TRANGTHAI NVARCHAR(50)
)

CREATE TABLE HOCKY(
	IDHOCKY  INT IDENTITY(1,1) PRIMARY KEY,
	IDNAMHOC VARCHAR(10) NOT NULL,
	TENHOCKY NVARCHAR(50),
	NGAYBATDAU DATE,
	NGAYKETTHUC DATE,
	TRANGTHAI NVARCHAR(50)
)

-- CODE NGÀY 25 / 4 

CREATE TABLE PHONGHOC(
	IDPHONGHOC INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
	TENPHONGHOC NVARCHAR(50),
	TRANGTHAI INT DEFAULT 0
)

CREATE TABLE LOP(
	IDLOP INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
	TENLOP NVARCHAR(50),
	KHOI INT,
	IDPHONGHOC INT,
	NAMVAOTRUONG INT
)


CREATE TABLE HOCSINH(
	MAHS VARCHAR(10) NOT NULL,
	TENHS NVARCHAR(50),
	NGAYSINH DATE,
	GIOITINH NVARCHAR(10),
	QUEQUAN NVARCHAR(50),
	DANTOC NVARCHAR(50),
	HOKHAU NVARCHAR(100),
	SDTPHUHUYNH VARCHAR(12),
	LINKAVATAR VARCHAR(50),
	TRANGTHAI VARCHAR(10),
	IDLOPHOC INT,
)
CREATE TABLE GIAOVIEN(
	IDGV VARCHAR(10) NOT NULL PRIMARY KEY,
	TENGV NVARCHAR(50),
	CMND VARCHAR(20),
	NGAYSINH DATE,
	GIOITINH NVARCHAR(10),
	QUEQUAN NVARCHAR(50),
	DANTOC NVARCHAR(50),
	HOKHAU NVARCHAR(100),
	SDT VARCHAR(12),
	EMAIL VARCHAR(50),
	LINKAVATAR VARCHAR(50),
	TRANGTHAI BIT
)